service: my-timetable-bot

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  environment:
    BOT_TOKEN: ${env:BOT_TOKEN}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /
          method: post
